// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axjtwrrymlmwuswzwlyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4anR3cnJ5bWxtd3Vzd3p3bHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTIxMzcsImV4cCI6MjA2MDM4ODEzN30.0oFa-7M5APXPuUFHxgTmRnNeXeH0UKnXR2UODtTc9MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);